openapi: 3.0.3
info:
  title: 'Django Rest Framework Football Api  '
  version: 0.0.0
paths:
  /api/:
    get:
      operationId: api_list
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CreateMatch'
          description: ''
  /api/remind/:
    post:
      operationId: api_remind_create
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SendEmail'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/SendEmail'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/SendEmail'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SendEmail'
          description: ''
components:
  schemas:
    CreateMatch:
      type: object
      properties:
        home_team:
          type: string
          maxLength: 100
        away_team:
          type: string
          maxLength: 100
        date:
          type: string
          format: date-time
        stadium:
          type: string
          maxLength: 100
      required:
      - away_team
      - date
      - home_team
      - stadium
    SendEmail:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        email:
          type: string
          format: email
          maxLength: 100
      required:
      - email
      - id
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
